services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flags
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - '8080:80'
    depends_on:
      - mysql

  ffm-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    depends_on:
      - mysql

  ffm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_NAME=flags
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=abc
      - JWT_EXP_IN=1h
    depends_on:
      - mysql
      - ffm-test

volumes:
  mysql_data:
